import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  public getProducts() {
    return [
      // Electronics
      {
        id: '1',
        name: 'Wireless Bluetooth Headphones',
        description: 'Over-ear headphones with active noise cancellation and 30-hour battery life.',
        price: 89.99,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
        rating: 4.5,
        reviewCount: 342,
        inStock: true,
        category: 'Electronics',
      },
      {
        id: '2',
        name: 'Smart Watch Series 5',
        description: 'Fitness tracking smartwatch with heart rate monitor and GPS.',
        price: 249.99,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
        rating: 4.3,
        reviewCount: 567,
        inStock: true,
        category: 'Electronics',
      },
      {
        id: '4',
        name: 'Portable Bluetooth Speaker',
        description: 'Waterproof speaker with deep bass and 12-hour playtime.',
        price: 39.99,
        imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500',
        rating: 4.6,
        reviewCount: 890,
        inStock: false,
        category: 'Electronics',
      },
      {
        id: '7',
        name: 'Noise Cancelling Earbuds',
        description: 'Compact true wireless earbuds with crystal-clear sound.',
        price: 119.99,
        imageUrl: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=500',
        rating: 4.7,
        reviewCount: 678,
        inStock: true,
        category: 'Electronics',
      },

      // Home
      {
        id: '8',
        name: 'Ceramic Coffee Mug Set',
        description: 'Set of 4 minimalist ceramic mugs, microwave and dishwasher safe.',
        price: 29.99,
        imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=500',
        rating: 4.5,
        reviewCount: 143,
        inStock: true,
        category: 'Home',
      },
      {
        id: '10',
        name: 'Cotton Throw Blanket',
        description: 'Soft woven throw blanket perfect for couch or bed.',
        price: 34.99,
        imageUrl: 'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?w=500',
        rating: 4.6,
        reviewCount: 256,
        inStock: true,
        category: 'Home',
      },
      {
        id: '11',
        name: 'Indoor Plant Pot Set',
        description: 'Set of 3 ceramic planters with drainage holes, various sizes.',
        price: 27.99,
        imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=500',
        rating: 4.4,
        reviewCount: 198,
        inStock: false,
        category: 'Home',
      },
      {
        id: '12',
        name: 'Stainless Steel Cookware Set',
        description: '10-piece cookware set with non-stick coating and glass lids.',
        price: 149.99,
        imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=500',
        rating: 4.3,
        reviewCount: 334,
        inStock: true,
        category: 'Home',
      },
      {
        id: '14',
        name: 'Table Lamp with Wood Base',
        description: 'Modern bedside lamp with warm LED light and fabric shade.',
        price: 45.99,
        imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
        rating: 4.5,
        reviewCount: 221,
        inStock: true,
        category: 'Home',
      },

      // Accessories
      {
        id: '15',
        name: 'Leather Crossbody Bag',
        description: 'Genuine leather bag with adjustable strap and multiple compartments.',
        price: 69.99,
        imageUrl: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=500',
        rating: 4.6,
        reviewCount: 289,
        inStock: true,
        category: 'Accessories',
      },
      {
        id: '16',
        name: 'Classic Aviator Sunglasses',
        description: 'UV400 protection sunglasses with metal frame.',
        price: 24.99,
        imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
        rating: 4.3,
        reviewCount: 156,
        inStock: true,
        category: 'Accessories',
      },
      {
        id: '17',
        name: 'Stainless Steel Wrist Watch',
        description: 'Minimalist analog watch with leather strap.',
        price: 89.99,
        imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500',
        rating: 4.7,
        reviewCount: 423,
        inStock: false,
        category: 'Accessories',
      },
      {
        id: '18',
        name: 'Woven Leather Belt',
        description: 'Handcrafted braided leather belt with brass buckle.',
        price: 32.99,
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
        rating: 4.2,
        reviewCount: 98,
        inStock: true,
        category: 'Accessories',
      },
      {
        id: '19',
        name: 'Silk Printed Scarf',
        description: 'Lightweight silk scarf with floral print, 90x90cm.',
        price: 27.99,
        imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=500',
        rating: 4.4,
        reviewCount: 134,
        inStock: true,
        category: 'Accessories',
      },
      {
        id: '20',
        name: 'Beaded Statement Necklace',
        description: 'Handmade beaded necklace with gold-plated accents.',
        price: 22.99,
        imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
        rating: 4.5,
        reviewCount: 176,
        inStock: true,
        category: 'Accessories',
      },

      // Clothing
      {
        id: '21',
        name: 'Cotton Crew Neck T-Shirt',
        description: 'Soft 100% cotton t-shirt, available in multiple colors.',
        price: 19.99,
        imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
        rating: 4.3,
        reviewCount: 512,
        inStock: true,
        category: 'Clothing',
      },
      {
        id: '22',
        name: 'Slim Fit Denim Jeans',
        description: 'Stretch denim jeans with a modern slim fit cut.',
        price: 49.99,
        imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
        rating: 4.4,
        reviewCount: 387,
        inStock: true,
        category: 'Clothing',
      },
      {
        id: '23',
        name: 'Hooded Pullover Sweatshirt',
        description: 'Fleece-lined hoodie with kangaroo pocket and drawstring.',
        price: 44.99,
        imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
        rating: 4.6,
        reviewCount: 298,
        inStock: false,
        category: 'Clothing',
      },
      {
        id: '24',
        name: 'Wool Blend Overcoat',
        description: 'Tailored long coat for cold weather, available in 3 colors.',
        price: 159.99,
        imageUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=500',
        rating: 4.7,
        reviewCount: 165,
        inStock: true,
        category: 'Clothing',
      },
      {
        id: '25',
        name: 'Summer Floral Maxi Dress',
        description: 'Flowy maxi dress with floral print, perfect for summer.',
        price: 54.99,
        imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500',
        rating: 4.5,
        reviewCount: 243,
        inStock: true,
        category: 'Clothing',
      },
    ];
  }
}
